DROP VIEW public.V_ROLES;
DROP VIEW public.V_ACCOUNT;

CREATE TABLE ACCOUNT_VERSION (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_FK BIGINT                   NOT NULL,
  NAME       VARCHAR(128)             NOT NULL,
  LAST_NAME  VARCHAR(128)             NOT NULL,
  MAIL       VARCHAR(128)             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CREDENTIAL_VERSION (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_FK BIGINT                   NOT NULL,
  PASSWORD   VARCHAR(128)             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ACCOUNT (
  ID                    SERIAL PRIMARY KEY,
  USERNAME              VARCHAR(64) UNIQUE,
  ACCOUNT_VERSION_FK    BIGINT REFERENCES ACCOUNT_VERSION (ID),
  CREDENTIAL_VERSION_FK BIGINT REFERENCES CREDENTIAL_VERSION (ID),
  STATUS                VARCHAR(32)              NOT NULL, --APPROVED, LOCKED, DELETED, PENDING
  CREATED               TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE USER_ROLE (
  ID         SERIAL PRIMARY KEY NOT NULL,
  ACCOUNT_FK BIGINT             NOT NULL REFERENCES ACCOUNT (ID),
  ROLE       VARCHAR(16)        NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);


-- Types:
-- REGISTRATION_REQUEST,
-- REGISTRATION_CONFIRMATION_PENDING,
-- REGISTRATION_CONFIRMED,
-- REGISTRATION_FAILED,
-- PASSWORD_RESET_REQUEST,
-- PASSWORD_RESET_CONFIRMATION_PENDING,
-- PASSWORD_RESET_CONFIRMED,
-- PASSWORD_RESET_FAILED
CREATE TABLE ACCOUNT_ACTION (
  ID         SERIAL PRIMARY KEY,
  ACCOUNT_FK BIGINT NOT NULL REFERENCES ACCOUNT (ID),
  IP         VARCHAR(32),
  UUID       VARCHAR(64),
  TIME       TIMESTAMP WITH TIME ZONE,
  TYPE       VARCHAR(64),
  CONTEXT    VARCHAR(256)
);

------------------------------------ VIEWS -----------------------------------------

CREATE OR REPLACE VIEW V_ACCOUNT AS
  SELECT
    a.username,
    c.password,
    a.status
  FROM account a, credential_version c
  WHERE
    a.credential_version_fk = c.id
    AND
    a.status = 'APPROVED';



CREATE VIEW V_ROLES AS
  SELECT
    a.username,
    u.role,
    a.status
  FROM account a, user_role u
  WHERE
    a.id = u.account_fk
    AND
    a.status = 'APPROVED';

-------------------------------- TEST DATA ------------------------------------------

-- admin SHA-512-> 'x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ONxp3Y3pB37A=='

-- admin SHA-256-> 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg='

-- Generate 'admin' SH256 password hash
-- java -cp $WILDFLY_HOME/modules/system/layers/base/org/picketbox/main/picketbox-4.0.21.Final.jar org.jboss.security.Base64Encoder admin SHA-256

INSERT INTO ACCOUNT (ID, USERNAME, STATUS, CREATED) VALUES (DEFAULT, 'login', 'APPROVED', CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT_VERSION (ID, ACCOUNT_FK, NAME, LAST_NAME, MAIL, CREATED) VALUES (DEFAULT, 1, 'Name', 'LastName', '********', CURRENT_TIMESTAMP);
INSERT INTO CREDENTIAL_VERSION (ID, ACCOUNT_FK, PASSWORD, CREATED) VALUES (DEFAULT, 1, '*******', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 1, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 1, 'USER', CURRENT_TIMESTAMP);
UPDATE ACCOUNT SET ACCOUNT_VERSION_FK = 1, CREDENTIAL_VERSION_FK = 1 WHERE ID = 1;

INSERT INTO ACCOUNT (ID, USERNAME, STATUS, CREATED) VALUES (DEFAULT, 'login', 'APPROVED', CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT_VERSION (ID, ACCOUNT_FK, NAME, LAST_NAME, MAIL, CREATED) VALUES (DEFAULT, 2, 'Name', 'LastName', '********', CURRENT_TIMESTAMP);
INSERT INTO CREDENTIAL_VERSION (ID, ACCOUNT_FK, PASSWORD, CREATED) VALUES (DEFAULT, 2, '*******', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 2, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 2, 'USER', CURRENT_TIMESTAMP);
UPDATE ACCOUNT SET ACCOUNT_VERSION_FK = 2, CREDENTIAL_VERSION_FK = 2 WHERE ID = 2;

INSERT INTO ACCOUNT (ID, USERNAME, STATUS, CREATED) VALUES (DEFAULT, 'login', 'APPROVED', CURRENT_TIMESTAMP);
INSERT INTO ACCOUNT_VERSION (ID, ACCOUNT_FK, NAME, LAST_NAME, MAIL, CREATED) VALUES (DEFAULT, 3, 'Name', 'LastName', '*********', CURRENT_TIMESTAMP);
INSERT INTO CREDENTIAL_VERSION (ID, ACCOUNT_FK, PASSWORD, CREATED) VALUES (DEFAULT, 3, '********', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 3, 'ADMIN', CURRENT_TIMESTAMP);
INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED) VALUES (DEFAULT, 3, 'USER', CURRENT_TIMESTAMP);
UPDATE ACCOUNT SET ACCOUNT_VERSION_FK = 3, CREDENTIAL_VERSION_FK = 3 WHERE ID = 3;

---------------------------------------------------------------------------------------