CREATE TABLE ACTIVITY_TRACKING (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_ID BIGINT                   NOT NULL,
  IP_ADDRESS VARCHAR(32)              NOT NULL,
  ACTION     VARCHAR(32)              NOT NULL,
  VIEW       VARCHAR(32)              NOT NULL,
  CONTEXT    VARCHAR(256)             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);


