CREATE TABLE ACCOUNT_VERSION (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_FK BIGINT                   NOT NULL,
  NAME       VARCHAR(128)             NOT NULL,
  LAST_NAME  VARCHAR(128)             NOT NULL,
  MAIL       VARCHAR(128)             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE CREDENTIAL_VERSION (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_FK BIGINT                   NOT NULL,
  PASSWORD   VARCHAR(128)             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ACCOUNT (
  ID                    SERIAL PRIMARY KEY,
  USERNAME              VARCHAR(64) UNIQUE,
  ACCOUNT_VERSION_FK    BIGINT REFERENCES ACCOUNT_VERSION (ID),
  CREDENTIAL_VERSION_FK BIGINT REFERENCES CREDENTIAL_VERSION (ID),
  STATUS                VARCHAR(32)              NOT NULL, --APPROVED, LOCKED, DELETED, PENDING
  CREATED               TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE USER_ROLE (
  ID         SERIAL PRIMARY KEY NOT NULL,
  ACCOUNT_FK BIGINT             NOT NULL REFERENCES ACCOUNT (ID),
  ROLE       VARCHAR(16)        NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE REGISTRATION (
  ID                SERIAL PRIMARY KEY,
  ACCOUNT_FK        BIGINT NOT NULL REFERENCES ACCOUNT (ID),
  IP                VARCHAR(32),
  REGISTRATION_UUID VARCHAR(64),
  REQUEST_DATE      TIMESTAMP WITH TIME ZONE,
  CONFIRMATION_DATE TIMESTAMP WITH TIME ZONE,
  STATUS            VARCHAR(32) -- CONFIRMED, DECLINED, CONFIRMATION_PENDING
);

CREATE TABLE PASSWORD_RESET (
  ID                    SERIAL PRIMARY KEY,
  ACCOUNT_FK            BIGINT REFERENCES ACCOUNT (ID),
  CREDENTIAL_VERSION_FK BIGINT REFERENCES CREDENTIAL_VERSION (ID),
  IP                    VARCHAR(32),
  PASSWORD_RESET_UUID   VARCHAR(64),
  REQUEST_DATE          TIMESTAMP WITH TIME ZONE,
  CONFIRMATION_DATE     TIMESTAMP WITH TIME ZONE,
  STATUS                VARCHAR(32) -- CONFIRMED, DECLINED, CONFIRMATION_PENDING
);

-- admin SHA-512-> 'x61Ey612Kl2gpFL56FT9weDnpSo4AV8j8+qx2AuTHdRyY036xxzTTrw10Wq3+4qQyB+XURPWx1ONxp3Y3pB37A=='
-- admin SHA-256-> 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg='

-- Generate 'admin' SH256 password hash
-- java -cp $WILDFLY_HOME/modules/system/layers/base/org/picketbox/main/picketbox-4.0.21.Final.jar org.jboss.security.Base64Encoder admin SHA-256

INSERT INTO ACCOUNT (ID, USERNAME, STATUS, CREATED)
VALUES (DEFAULT, 'admin', 'APPROVED', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT_VERSION (ID, ACCOUNT_FK, NAME, LAST_NAME, MAIL, CREATED)
VALUES (DEFAULT, 1, 'Artjoms', 'Stukans', 'artjoms.stukans@gmail.com', CURRENT_TIMESTAMP);

INSERT INTO CREDENTIAL_VERSION (ID, ACCOUNT_FK, PASSWORD, CREATED)
VALUES (DEFAULT, 1, 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=', CURRENT_TIMESTAMP);

INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED)
VALUES (DEFAULT, 1, 'ADMIN', CURRENT_TIMESTAMP);

INSERT INTO USER_ROLE (ID, ACCOUNT_FK, ROLE, CREATED)
VALUES (DEFAULT, 1, 'USER', CURRENT_TIMESTAMP);

UPDATE ACCOUNT
SET ACCOUNT_VERSION_FK = 1, CREDENTIAL_VERSION_FK = 1
WHERE ID = 1;
