-- Create sequence for students.
DROP SEQUENCE public.FAKTURA_REPORT_ID_SEQUENCE RESTRICT;
CREATE SEQUENCE FAKTURA_REPORT_ID_SEQUENCE START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

CREATE OR REPLACE FUNCTION getFakturaId()
  RETURNS BIGINT AS
  $$
  BEGIN
    RETURN nextval('FAKTURA_REPORT_ID_SEQUENCE');
  END;
  $$ LANGUAGE plpgsql;