-- Create sequence for balance.
CREATE SEQUENCE BALANCE_SEQUENCE START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Create file table.
CREATE TABLE BALANCE
(
  BALANCE_ID BIGINT       NOT NULL    DEFAULT nextval('BALANCE_SEQUENCE'),
  STUDENT_FK BIGINT       NOT NULL,
  VALUE      INT          NOT NULL    DEFAULT 0,
  COMMENTS   VARCHAR(256) NOT NULL,
  STATUS     VARCHAR(64)  NOT NULL    DEFAULT 'SUBMITTED', --SUBMITTED, DELETED
  CREATED    TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT BALANCE_PKEY PRIMARY KEY (BALANCE_ID)
);

