DROP VIEW public.v_student_balance RESTRICT;
DROP TABLE public.student_balance;
DROP SEQUENCE public.student_balance_sequence RESTRICT;

-- Create sequence for balance.
CREATE SEQUENCE STUDENT_BALANCE_SEQUENCE START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Create file table.
CREATE TABLE STUDENT_BALANCE
(
  BALANCE_ID BIGINT      NOT NULL     DEFAULT nextval('STUDENT_BALANCE_SEQUENCE'),
  STUDENT_FK BIGINT      NOT NULL REFERENCES STUDENTS_VERSION_MAPPING (STUDENT_FK),
  AMOUNT     INT         NOT NULL,
  COMMENTS   VARCHAR(256),
  STATUS     VARCHAR(64) NOT NULL     DEFAULT 'SUBMITTED', --SUBMITTED, DELETED
  CREATED    TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UPDATED    TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT STUDENT_BALANCE_PKEY PRIMARY KEY (BALANCE_ID)
);


CREATE OR REPLACE VIEW v_student_balance AS
  SELECT
    student_fk,
    sum(amount)
  FROM student_balance
  WHERE STATUS = 'SUBMITTED'
  GROUP BY student_fk;