DROP VIEW public.V_STUDENT_DOCUMENTS;
DROP TABLE public.STUDENT_DOCUMENTS;
DROP SEQUENCE public.STUDENT_DOCUMENTS_SEQUENCE RESTRICT;

-- Create sequence for balance.
CREATE SEQUENCE STUDENT_DOCUMENTS_SEQUENCE START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- Create file table.
CREATE TABLE STUDENT_DOCUMENTS
(
  DOCUMENT_ID BIGINT      NOT NULL     DEFAULT nextval('STUDENT_DOCUMENTS_SEQUENCE'),
  FILE_FK BIGINT NOT NULL REFERENCES files (FILE_ID),
  STUDENT_FK  BIGINT      NOT NULL REFERENCES students_version_mapping (STUDENT_FK),
  STATUS      VARCHAR(64) NOT NULL, --SAVED,DELETED
  CREATED     TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UPDATED     TIMESTAMP WITH TIME ZONE DEFAULT now(),
  CONSTRAINT STUDENT_DOCUMENTS_PKEY PRIMARY KEY (DOCUMENT_ID)
);

CREATE OR REPLACE VIEW V_STUDENT_DOCUMENTS AS
  SELECT
    s.document_id,
    s.file_fk,
    s.student_fk,
    s.created,
    t.name,
    t.size
  FROM STUDENT_DOCUMENTS s, files t
  WHERE
    s.FILE_FK = t.file_id
    AND s.status = 'SAVED';