CREATE TABLE CREDENTIALS (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_ID BIGINT                   NOT NULL,
  PASSWORD   VARCHAR(128)             NOT NULL,
  STATUS     VARCHAR(32)              NOT NULL, --ACTIVE, INACTIVE
  CREATED    TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ACCOUNT_VERSION (
  USERNAME VARCHAR(64) PRIMARY KEY,
  ID       BIGINT NOT NULL
);


CREATE TABLE ACCOUNT (
  ID         SERIAL PRIMARY KEY       NOT NULL,
  ACCOUNT_ID BIGINT                   NOT NULL,
  USERNAME   VARCHAR(64)              NOT NULL,
  NAME       VARCHAR(128)             NOT NULL,
  LAST_NAME  VARCHAR(128)             NOT NULL,
  E_MAIL     VARCHAR(128)             NOT NULL,
  STATUS     VARCHAR(32)              NOT NULL, --APPROVED, LOCKED, DELETED, PENDING
  CREATED    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE ROLE (
  ID          SERIAL PRIMARY KEY       NOT NULL,
  ROLE        VARCHAR(128)             NOT NULL,
  DESCRIPTION VARCHAR(128)             NOT NULL
);

CREATE TABLE USER_ROLE (
  ID         SERIAL PRIMARY KEY NOT NULL,
  ACCOUNT_ID BIGINT             NOT NULL,
  ROLE_ID    BIGINT             NOT NULL,
  CREATED    TIMESTAMP WITH TIME ZONE
);

-- java -cp $WILDFLY_HOME/modules/system/layers/base/org/picketbox/main/picketbox-4.0.21.Final.jar org.jboss.security.Base64Encoder admin SHA-256

INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES (DEFAULT, 'ADMIN', 'Administrator');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES (DEFAULT, 'USER', 'User');
INSERT INTO ROLE (ID, ROLE, DESCRIPTION) VALUES (DEFAULT, 'GUEST', 'Guest');

INSERT INTO ACCOUNT (ID, ACCOUNT_ID, USERNAME, NAME, LAST_NAME, E_MAIL, STATUS, CREATED)
VALUES (DEFAULT, 1, 'admin', 'Artjoms', 'Stukans', 'artjoms.stukans@gmail.com', 'APPROVED', CURRENT_TIMESTAMP);

INSERT INTO CREDENTIALS (ID, ACCOUNT_ID, PASSWORD, STATUS, CREATED)
VALUES (DEFAULT, 1, 'jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=', 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO ACCOUNT_VERSION (USERNAME, ID)
VALUES ('admin', 1);

INSERT INTO USER_ROLE (ID, ACCOUNT_ID, ROLE_ID, CREATED)
VALUES (DEFAULT, 1, 1, CURRENT_TIMESTAMP);

INSERT INTO USER_ROLE (ID, ACCOUNT_ID, ROLE_ID, CREATED)
VALUES (DEFAULT, 1, 2, CURRENT_TIMESTAMP);
